### PR TITLE
Tests and fix the infinite recursion issue

### LINKED ISSUE #1: Cannot trap incorrect onewire sensor address
When an incorrect onewire device address is used then AttributeError is never reached, as the self.attrs property appears to cause an infinite recursion spiral. See http://stackoverflow.com/questions/41086460/cannot-trap-python-exception-from-imported-module for more details. I have tried the fix suggested by Luke Woodward and this works for me and has got me out of a hole.

### PR DESCRIPTION
**Pull request by Emantor**
This adds a test for the recursion issue, configures travis and fixes the issue.
I'm not entirely sure this is how we want to fix it, but it is one solution to our problem.
Feedback highly welcome!

Fix #1

### CODE REVIEW

**Comment by Emantor** [comment]
Ping, any updates on this?

**Comment by kipe** [comment]
Hey, sorry for the latency, way too busy with work.
It looks like this breaks the initial reason for using `__getattr__`, I'd like this library to be (almost) compatible with the original `ow` -implementation.
In essence, the variables of the sensor / IO should be accessible via `Sensor.temperature`, which means using `__getattr__` and `__setattr__` to access the variables.

**Comment by kipe** [comment]
Forgot to link the original inspiration [Python: package ow](http://owfs.sourceforge.net/owpython.html). The reason why I started re-writing this was that there was no Python3 -compatible version of this.

**Comment by Emantor** [comment]
Thanks for the update. I'll come up with another solution that does not involve renaming the function, let me think on this 👍

**Comment by Emantor** [comment]
I removed the rename, please have a look at the PR again.

**Comment by Emantor** [comment]
Ping, I'd like an update on this, we want to release our library and depend in parts on this module.

**Comment by kipe** [comment]
Sorry for the delay, been extremely busy with work. This looks fine, don't have time to test it at the moment, but I trust it works ;)

**Comment by Emantor** [comment]
Thats why I added the test :) Thank you for taking the time! 👍

**Pull request merged**
